### ISSUE TITLE
Cluster Problem: returned NULLs

### ISSUE THREAD

**Issue by dantaki** [rqtl/qtl2#101]
I'm using qtl2 to find eQTLs in DO mice (N=182). I attempted to perform a genome-wide scan using a kinship matrix. I got this error:

```
Error in scan1_pg_clean(genoprobs, these2keep, Ke, ph, ac, ic, is_x_chr, : 
  cluster problem: returned 251773 NULLs
```

I think this might be due to resource limitations (memory)? I am running qtl2 on my workstation with 32GB of RAM, which might not be enough.

```
library(qtl2)
dat <- read_cross2("do.eqtl.json")
map <- insert_pseudomarkers(dat$gmap, step=1)
pr <- calc_genoprob(dat, map, error_prob=0.002,cores=12)
kinship <- calc_kinship(pr,cores=12)
Xcovar <- get_x_covar(dat)
### GENOME SCAN ###
apr <- genoprob_to_alleleprob(pr)
out_pg <- scan1(apr, dat$pheno, kinship, Xcovar=Xcovar, cores=8)
```

I processed the DO genotypes from GigaMUGA arrays as shown in your tutorial. 

It seems that the best approach is to run the scan for each chromosome separately. But if I do this should I calculate a chromsome kinship matrix or use the one I made from the whole array?

Thanks!

**Comment by kbroman** [comment]
Maybe save the `pr` object to disk and remove it from your R workspace, to make free up RAM?

How many phenotypes do you have, and how many markers/pseudomarkers are you using? (That is, how big is the `apr` object?) The output `out_pg` is going to be no. positions x no. phenotypes, which can get really large.

I prefer to use `method="loco"`with the kinship matrix. But whether you scan the chromosomes one at a time or all together, it shouldn't affect your choice of kinship matrix.

I'd switch to single-core and scan just a few phenotypes, to try to identify the cause of the error.

(Would you be willing to join the R/qtl2 discussion group (https://groups.google.com/group/Rqtl2-disc) and submit questions there? I'm trying to steer questions there, and leave the Issues for bug reports.)

**Comment by dantaki** [comment]
Thanks for the quick response. I think I can take it from here and if I have any questions I'll post to the google group. Thanks!
