### ISSUE TITLE
`zip_datafiles` throws error if data in different directory

### ISSUE THREAD

**Issue by tavareshugo** [rqtl/qtl2#102]
`zip_datafiles()` seems to throw an error when data are in a sub-directory. Here's an example:

```r
# work from temporary directory
setwd(tempdir())

# create a sub-directory
dir.create("data")

# download example data in there
download.file("https://github.com/rqtl/qtl2data/raw/master/ArabMAGIC/arabmagic.zip", 
              "data/qtl2data.zip", "wget")

# unzip contents
unzip("data/qtl2data.zip", exdir = "data")

# create new zip_datafiles - error
qtl2::zip_datafiles("./data/arabmagic.json")
```

I think the problem is in lines [76-79 of function](https://github.com/rqtl/qtl2/blob/393b00fc84199140869fb7b035317e35c04a3c83/R/zip_datafiles.R#L76-L79), which change working directory, but then line [99](https://github.com/rqtl/qtl2/blob/393b00fc84199140869fb7b035317e35c04a3c83/R/zip_datafiles.R#L99) uses `zip_file` that includes the full path. Not sure lines 76-79 are necessary at all?

**Comment by kbroman** [comment]
I think the problem I had was preventing the zip file from containing the full depth of directories.

**Comment by kbroman** [comment]
Hi, @tavareshugo, It should be working now; thanks for reporting the problem, and particularly for providing the example!
