### ISSUE TITLE
double_kinship

### ISSUE THREAD

**Issue by dckatz** [rqtl/qtl2#120]
With respect to kinship in a mixed model scan, it looks like scan1perm uses K*2 (following the reasons in the reference noted in the script), while scan1 does not scale K. Is that correct?

**Comment by kbroman** [comment]
There should be a call to `double_kinship()` in each of them, for example [`scan1_pg.R` line 48](https://github.com/rqtl/qtl2/blob/master/R/scan1_pg.R#L48)

**Comment by dckatz** [comment]
I see it now. Sorry I didn't look through to scan1_pg.
