### ISSUE TITLE
RIL self warning message on reading cross

### ISSUE THREAD

**Issue by jlboat** [rqtl/qtl2#153]
Hello,

I'm performing QTL mapping on a RIL (via selfing) population, and I have some questions about a warning message that I either get or don't get depending on the qtl2 version when reading the cross.

The warning is:
Warning message:
In check_cross2(output) : 295091 invalid genotypes in cross

The warning is not printed in qtl2_0.20, but it is printed in qtl2_0.21-19. It definitely corresponds to the B genotype in the example below (since that count above = the number of B in my geno file).

YAML file: 
crosstype: riself
geno: Pop6.qchetero.corrected.rqtl.csv
pheno: phenotypes.csv
gmap: gmap.csv
pmap: pmap.csv
alleles:
- A
- B
genotypes:
  A: 1
  H: 2
  B: 3
na.strings:
- "-"
- NA

Admittedly, this format does not exactly follow the example posted, but the examples have either:
genotypes:
  AA: 1
  BB: 2
OR
alleles:
- L
- C
genotypes:
  L: 1
  C: 2

I'm attempting to use ABH format (ex. Line_020,-,B,A,B,A,-,A,A,A,H,H...), which may be completely deprecated, but I'm not sure how best to account for het calls that remain in our population and feel that replacing with missing characters would be a loss of information.

Any thoughts on the matter would be appreciated. Thanks.

**Comment by kbroman** [comment]
R/qtl2 doesn’t allow hets in cross type “riself”, and the genotypes get converted to numbers 1 and 2.  So where you have 

A: 1
H: 2
B: 3

you need to just put

A: 1
B: 2

and just allow the H’s to be omitted as missing. 

karl

**Comment by jlboat** [comment]
Got it. Thanks for responding so quickly.
