### ISSUE TITLE
convert vcf file of an haploid to run r/qtl or r/qtl2

### ISSUE THREAD

**Issue by jeancarlier34** [rqtl/qtl2#205]
Hello,

I work on an haploid fungus. I have SNP data in a vcf from a cross between 2 strains that I would like to use to construct a genetic map using r/qtl. What are the functions I could used to convert the vcf (encoded for an haploid, see below a sample of the first line)?

scaffold_1	316761	.	T	G	24186.3	.	AC=90;AF=0.486;AN=185;BaseQRankSum=0.00;DP=2570;FS=0.000;MLEAC=92;MLEAF=0.497;MQ=59.69;MQRankSum=0.00;QD=33.50;ReadPosRankSum=0.00;SOR=0.264	GT:AD:DP:GQ:PL	1:0,4:4:99:99,0	0:4,0:4:99:0,99	1:0,5:5:99:144,0

Many thanks,
Jean

**Comment by kbroman** [comment]
There are no particular functions for converting vcf files to R/qtl2 format, but see [vcftools](https://vcftools.github.io/) or the [vcfR package](https://knausb.github.io/vcfR_documentation/) and [this discussion](https://groups.google.com/g/rqtl2-disc/c/0mwrvoDEp_c/m/Z-RLlynNBAAJ) at the [R/qtl2 google group](https://groups.google.com/g/rqtl2-disc).
