### ISSUE TITLE
Can I use already existed probability data into qtl2

### ISSUE THREAD

**Issue by BoraKim2018** [rqtl/qtl2#206]
Attachments: 
[Genetic_map_MM_PI_Sterken_etal.csv](https://github.com/rqtl/qtl2/files/8002792/Genetic_map_MM_PI_Sterken_etal.csv)
[genotypes.csv](https://github.com/rqtl/qtl2/files/8002871/genotypes.csv)
[phenotypes_median_test.csv](https://github.com/rqtl/qtl2/files/8002874/phenotypes_median_test.csv)
[physical_map.csv](https://github.com/rqtl/qtl2/files/8002877/physical_map.csv)

Hello, thank you very much for developing this nice package. I am very new to QTL mapping and R/qtl2, and I would greatly appreciate to get any help. 

To begin with, I would like to do QTL analysis with the data from tomato RIL population (two parents, F8 selfing). 
I've got mapfile (Genetic_map_MM_PI_Sterken_etal.csv) from the paper "Plasticity of maternal environment dependent expression-QTLs, 2020 (https://www.biorxiv.org/content/10.1101/2021.03.29.437558v2.full)" that contains physical map (Mbp) and the estimation of being one of parents, Moneymaker or Pimpinellifolium, base on the SNPs on each locus. 

- To make it workable in R/qtl2, all the numbers < 0.5 were converted to A and >=0.5 to B (genotypes.csv).
- Physical map was separated from the original map file (Physical_map.csv). 
- Before I conduct full analysis, I tried QTL mapping with small set of phenotype (phenotypes_median_test.csv) that is tomato shoot weight to see if everything is going well . 

Then I wrote control file as below.

```
control_test <- file.path("~/RIL_data_analysis", "control_test.yaml")
write_control_file(control_test,
                   crosstype="riself",
                   geno_file="genotypes.csv",
                   gmap_file="physical_map.csv",
                   pmap_file="physical_map.csv",
                   pheno_file="phenotypes_median_test.csv",
                   geno_codes=c(A=1L, B=2L),
                   alleles=c("A", "B"),
                   na.strings=c("-", "NA"))

test <- read_cross2("control_test.yaml")
```

1. **My first question here is, is it correct to choose crosstype="rilself"?** I am not very confident about my decision. 

Then, I added pseudomarkers to my physical map and calculated the genotype probability.

```
map <- insert_pseudomarkers(map=test$pmap, step=10000)
pr <- calc_genoprob(cross=test, map=map, error_prob=0.001) 
```

As a result, I found that SNP marker genotype probability is either 0.999 or 0.001 for AA and BB, respectively. However, all pseudomarkers probability became 0.5. 

```
> pr$ch01[1:10,,"snp5"]
         AA    BB
T_MM  0.999 0.001
T_251 0.001 0.999
T_205 0.999 0.001
T_206 0.999 0.001
T_207 0.999 0.001
T_208 0.001 0.999
T_209 0.999 0.001
T_210 0.999 0.001
T_211 0.999 0.001
T_212 0.999 0.001

> pr$ch01[1:10,,"cch01.loc50000"]
       AA  BB
T_MM  0.5 0.5
T_251 0.5 0.5
T_205 0.5 0.5
T_206 0.5 0.5
T_207 0.5 0.5
T_208 0.5 0.5
T_209 0.5 0.5
T_210 0.5 0.5
T_211 0.5 0.5
T_212 0.5 0.5
```

I understood this as the SNP marker probability is roughly 1 or 0. So, pseduomarkers in between markers inevitably 0.5.
So at the end, I could run all following steps such as `scan_1`, but of course, without LOD scores at all pseudomarkers. So, it was basically the same as an analysis without adding pseudomarkers. 

2.  **Therefore, here's my second question: The original map file (Genetic_map_MM_PI_Sterken_etal.csv) already contains probability scores, and is there way to assign it as qtl2 object and use it directly to `scan_1`?** 

Thank you in advance for your time.

**Comment by kbroman** [comment]
Could you post your questions to the [R/qtl2 google group](https://groups.google.com/g/rqtl2-disc)? I would prefer to answer them there, and use the github issues only for bug reports.
