### ISSUE TITLE
Can I generate a genetic map with R/qtl2?

### ISSUE THREAD

**Issue by Jiseon623** [rqtl/qtl2#208]
Hello
Thank you so much for your great tools, R/qtl and R/qtl2.

I have one question for using R/qtl2. Is it fully replacable for R/qtl?
I want to generate a genetic map for my species, which have no chromosome-level genome assembly. I have a long-read sequencing-based genome assembly and short-read sequencing data of 50 individuals that were generated by crossing two highly inbred lines and following ~30x random mating. My species have a ~150 Mb-sized genome and the two biparental lines have ~1M variants.

I read your R/qtl2 paper, and I found that more than 100 markers is large enough for R/qtl. So if possible, I'd like to use R/qtl2 rather than R/qtl. However, I cannot find any tutorial for generating a genetic map using R/qtl2.
I'd be grateful if you let me know whether it is possible or not, and if possible, how to do creating a genetic map.

Thank you in advance

**Comment by kbroman** [comment]
We have not yet implemented genetic map construction functions in R/qtl2, except for re-estimating the inter-marker distances, given a fixed order. And so, de novo map construction is not currently available in R/qtl2.

R/qtl2 handles multi-parent populations and genome scans with a linear mixed model. But it doesn’t yet include multiple-QTL models or genetic map construction.

We prefer to get questions for R/qtl2 at the [Google Group](https://groups.google.com/forum/#!forum/rqtl2-disc), leaving issues in the github repository for bug reports.

**Comment by Jiseon623** [comment]
Thank you for your kind answer.

I'm sorry for repeating other users' questions.
I read your previous answers to the same questions where you have mentioned that you are not developing such tools for R/qtl2.
Could you recommend alternative tools for constructing a genetic map using high-dense markers?

Thank you in advance
