### ISSUE TITLE
yaml and genotype file format

### ISSUE THREAD

**Issue by yifangt** [rqtl/qtl2#213]
I have two questions about the input data:
1) In the control YAML file, what is the exact format of the **phenocovar:** line when there is no phenotype covariate?  Simply omit the line?
2) In the genotype file, what is the easy way to transpose the dataframe when rows are for markers and columns are for sampleIDs? In the package example data (_grav2_geno.csv_), the format is columns for markers and rows for sampleIDs. In practice when there are hundred thousands of markers (say SNPs), this could be a challenge to transpose the matrix/dataframe. The Excel (at least early versions) sheet has limit number of total columns, but the row number is normally big enough to hold millions of SNPs.
Thanks!

**Comment by kbroman** [comment]
> I have two questions about the input data:
>
>    1. In the control YAML file, what is the exact format of the
>    *phenocovar:* line when there is no phenotype covariate? Simply omit
>    the line?
>
>
Yes, omit the line.


>
>    1. In the genotype file, what is the easy way to transpose the
>    dataframe when rows are for markers and columns are for sampleIDs? In the
>    package example data (*grav2_geno.csv*), the format is columns for
>    markers and rows for sampleIDs. In practice when there are hundred
>    thousands of markers (say SNPs), this could be a challenge to transpose the
>    matrix/dataframe. The Excel (at least early versions) sheet has limit
>    number of total columns, but the row number is normally big enough to hold
>    millions of SNPs.
>
>
Use geno_transposed: true

See, for example, the json control file for the BXD data:
https://github.com/rqtl/qtl2data/blob/main/BXD/bxd.json#L18
There are a number of additional sample datasets at
https://github.com/rqtl/qtl2data/

karl
