### ISSUE TITLE
Add explanation of weights in est_herit

### ISSUE THREAD

**Issue by gtsambos** [rqtl/qtl2#221]
Hi Karl (and others), thanks for all the amazing work you've put into making r/qtl2 such a useful tool! I'm messaging because of a specific problem I'm having using the `est_herit` function along with the `weights` parameter, documented [here](https://search.r-project.org/CRAN/refmans/qtl2/html/est_herit.html).

 My estimated heritability values change drastically when I multiply all of the weights by a constant scalar (eg. to normalise them). I would have expected that the estimates would be invariant with respect to this operation. I'm wondering if there is some other constraint on these `weights` that I might be missing or misunderstanding? 

 A snippet of the code I'm running is is below. I create a vector of weights called `weights`, and then another vector called `weights1` which is just a scaled copy of `weights`. I estimate heritability using each of these, with all other arguments unchanged, and get very different heritabilities (these are called `PC_coordX` in the printed output).

R code:

```r
# Read in weights (the number of generations of filial inbreeding).
weights <- read.csv(opt$weights, header=TRUE, sep="\t", row.names=1)
weights <- as.double(weights$NumFilialGens)

# Normalise the weights.
weights1 <- weights/sum(weights)

# Set names.
weights <- setNames(weights, bxd_names)
weights1 <- setNames(weights1, bxd_names)
rownames(pheno) <- bxd_names

# Estimate heritability
hsq <- est_herit(pheno=pheno, kinship=k, weights=weights)
hsq1 <- est_herit(pheno=pheno, kinship=k, weights=weights1)
```

Printed output:

```
> print(hsq)

  PC1_coord   PC2_coord   PC3_coord   PC4_coord   PC5_coord   PC6_coord 

0.018682377 0.004905916 0.011374136 0.005229924 0.008185645 0.005286264 

...
> print(hsq1)

PC1_coord PC2_coord PC3_coord PC4_coord PC5_coord PC6_coord 

0.9918696 0.9693177 0.9866174 0.9711729 0.9814425 0.9714729 

...
```

**Comment by kbroman** [comment]
Sorry; we don't seem to have included any real explanation of the weights.

The model that is fit has variance matrix V = sigma^2 [ h^2 K + (1-h^2) V_e]  where K is the kinship matrix and V_e is a diagonal matrix with the set of weights provided.  Multiplying the weights by a constant will affect h^2.

**Comment by gtsambos** [comment]
ah, okay. Yes I'd assumed the weights were sample weights, like in weighted least squares

**Comment by gtsambos** [comment]
thanks for the clarification!
