### ISSUE TITLE
qtl2::read_csv() masks readr::read_csv()

### ISSUE THREAD

**Issue by micwij** [rqtl/qtl2#223]
When trying to read in my dataset with read_csv() while having qtl2 loaded, I noticed, that it does not work and saw that qtl2 also has a read_csv() function. I think it would make sense to name this function fread_csv() since it is based on the data.table::fread() function and to avoid masking readr::read_csv().

**Comment by kbroman** [comment]
Good idea; thanks!

**Comment by kbroman** [comment]
Fixed in [this commit](https://github.com/rqtl/qtl2/commit/83301f7744648a4ad279cf61d5cc5123abb3846a): renamed `read_csv()` as `fread_csv()` and `read_csv_numer()` as `fread_csv_numer()`.
