### ISSUE TITLE
Effects of using pmap instead of gmap

### ISSUE THREAD

**Issue by micwij** [rqtl/qtl2#224]
I am analysing a dataset, for which I only have a physical map of marker positions. I partially followed the vignette and used pmap whenever gmap was used. The read_cross2() function call gives a warning that "gmap is missing" but otherwise the functions seem to also work with a pmap. Is this okay to do? Would it be beneficial to also have the genetic map and can I generate it in qtl2? I guess these are trivial questions for experienced users, but maybe this information could also be provided in the Vignette.

**Comment by kbroman** [comment]
For the calculation of genotype probabilities, or genotype imputation, we need recombination fractions for each interval, which is obtained from the genetic length using a map function. 

With dense, high quality genotype data, the genetic map may not be too critical, but I would at least attempt to get an approximate genetic map by rescaling the physical map using some estimate of the cM:Mbp recombination rate.

**Comment by kbroman** [comment]
I would prefer to get general questions about the use of the software not as GitHub Issues, but in the [R/qtl2 Google Group](https://groups.google.com/forum/#!forum/rqtl2-disc), and to leave issues for specific software problems or bug reports.

**Comment by micwij** [comment]
I see. Thanks for the quick reply and for referring me to the group!
