### ISSUE TITLE
Genotype format conversion for multiparental MAGIC populations 123

### ISSUE THREAD

**Issue by jamonterotena** [rqtl/qtl2#226]
I'm trying to prepare the genotyping data from a multiparental MAGIC population by applying the described format 123 for AA, AB, BB. I have a PED file with PLINK genotyping format 0 1, where 0 stands for minor and 1 for major allele.

I'm struggling to find any way that is already available to convert from this 'allele-by-column' format to a 'SNP-by-column' format, which would enable to produce the required format.

I would appreciate if you could share any help on this issue :)

**Comment by kbroman** [comment]
You can leave it coded that way, and indicate that encoding in the control file. 

In `genotypes`, the [example we have looks like this](https://kbroman.org/qtl2/assets/vignettes/input_files.html):

```
genotypes:
  - SS: 1
  - SB: 2
  - BB: 3
```

But you could instead put:

```
genotypes:
  - 0: 1
  - 1: 3
```

I prefer to have the github issues for problems with the software, and questions about its use at the [R/qtl2 google group](https://groups.google.com/forum/#!forum/rqtl2-disc). If you can, please join the google group.
