### ISSUE TITLE
legend in plot_coefCC works only if scan1_output provided

### ISSUE THREAD

**Issue by kbroman** [rqtl/qtl2#33]
Issue raised at [qtl2plot package](https://github.com/rqtl/qtl2plot/issues/46):

> I am running the code below on a dataset containing DO mouse data, the legend does not display when I have the scan1_output parameter available. I've also tried using the legend parameter within plot_coefCC, but I get a warning message saying that the legend parameter is not a graphical parameter.
> 
> The legend, however, does work if the scan1_output is removed.
> 
> Any insights on how I can get the legend to display in a plot showing both allele coefficient and scan1 outputs?
 
```
plot_coefCC(x = add_coef, map = map_all[add_chr], scan1_output=add_lod)
legend("topright", col=CCcolors, names(CCcolors), ncol=2, lwd=2, bg="gray95")
```

**Comment by ytakemon** [comment]
Updating the qtl2 package fixed it. Cheers!
![screen shot 2018-02-02 at 8 19 07 am](https://user-images.githubusercontent.com/16295129/35735455-d45258f6-07f2-11e8-9531-a992a946ebd0.png)

**Comment by kbroman** [comment]
great!
