### ISSUE TITLE
please add find_snp and pull_snpprobpos routines 

### ISSUE THREAD

**Issue by byandell** [rqtl/qtl2#47]
I have use for the following type of functions that parallel `find_marker()` and `pull_genoprobpos()`. It may be that you can fool these routines into doing double duty, but I could not figure that out.

```
find_snp_id <- function(snpprobs, snpinfo, pos) {
  m <- match(dimnames(snpprobs[[1]])[[3]], snpinfo$snp_id)
  snpinfo$snp_id[m[which.min(abs(snpinfo$pos[m] - pos))]]
}
```

```
pull_snpprobpos <- function(snpprobs, snp_id) {
  snpprobs[[1]][,, snp_id]
}
```

**Comment by kbroman** [comment]
What I did isn't exactly what you asked for, but hopefully it will suffice.

`find_marker()` now will take a "snp info" table in place of the map. You can use that to find the SNP closest to a particular position, similar to your `find_snp_id()`, but not restricted to the indexed SNPs that are in the probabilities.

You can then use the new function `find_index_snp()` to find the name of the indexed SNP that corresponds to a particular SNP.

You can then use `pull_genoprobpos()` with the snp probabilities and the index SNP; I don't think there's a need for a separate `pull_snpprobpos()`.
