### ISSUE TITLE
create_ccvariants: founder names not same as CCcolors

### ISSUE THREAD

**Issue by byandell** [rqtl/qtl2#6]
The code in
https://github.com/rqtl/qtl2/blob/master/inst/scripts/create_ccvariants.R
pulls out 8 columns for the founder alleles using the names
"A_J","C57BL_6J","129S1_SvImJ","NOD_ShiLtJ","NZO_HlLtJ","CAST_EiJ","PWK_PhJ","WSB_EiJ"
However, CCcolors in
https://github.com/rqtl/qtl2/blob/master/data/CCcolors.RData
uses the names
"AJ","B6","129","NOD","NZO","CAST","PWK","WSB"
This creates a minor heading in building companion packages.
Brian

**Comment by kbroman** [comment]
Ah, sorry. But I'm inclined to leave these as they are. 

I think the names in the SNP database should reflect the real strain names (with `/` changed to `_`).

The names in `CCcolors`, on the other hand, I'd rather be short names that I can use in plots.
