### ISSUE TITLE
plot.scan1 forgets to pass lodcolumn to plot_snpasso

### ISSUE THREAD

**Issue by byandell** [rqtl/qtl2#7]
plot.scan1 <-
    function(x, map, lodcolumn=1, chr=NULL, add=FALSE, gap=25, ...)
{
    # if map looks like snpinfo, assume this is a snp asso result and use plot_snpasso()
    if(is.data.frame(map) && "index" %in% names(map)) {
        plot_snpasso(x, snpinfo=map, add=add, gap=gap, lodcolumn=lodcolumn, ...)
    }
    else { # mostly, use plot_scan1()
        plot_scan1(x, map=map, lodcolumn=lodcolumn, chr=chr, add=add, gap=gap, ...)
    }
}

**Comment by kbroman** [comment]
Fixed in PR #8.
